config { 
    type: "table" ,
    schema: "demo_silver",
    name: "joined_silver_kevin",
    assertions: {
        nonNull: [ "contract_id" ],
        uniqueKey: ["client_id"]
    }
}

select p.transaction_id
    , p.contract_id
    , p.client_id
    , TIMESTAMP_SECONDS(transaction_date) as transaction_date
    , p.payment_amt
    , p.payment_code
    , c.entity_type

from ${ref('payments')} p
Left Join ${ref('clients')} c on p.client_id = c.client_id