config { 
    type: "table" ,
    schema: "demo_silver",
    name: "joined_silver_kevin"
}
-- declare sourceTableName STRING DEFAULT 'payments';

select p.transaction_id
    , p.contract_id
    , p.client_id
    ,  TIMESTAMP_SECONDS(transaction_date) as transaction_date
    , p.payment_amt
    , p.payment_code
    , c.entity_type
    -- , c.entity_year_establish
from ${ref('payments')} p
Left Join ${ref('clients')} c on p.client_id = c.client_id